# Generated by Django 4.2.3 on 2023-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_from_crawler',
            field=models.CharField(max_length=3000),
        ),
    ]
