# Generated by Django 4.2.3 on 2023-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_description_from_crawler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_from_crawler',
            field=models.CharField(max_length=20000),
        ),
    ]
